---
  - name: Build image docker
     docker_image:
       name: student-list:latest
       build:
         path: /home/ec2-user/ansible/student-list/simple_api
       source: build
     tags: image_docker

   - name: Create private container's network
     docker_network:
       name: student-list
     tags: network

   - name: Start the container with the backend and connect it to the network
     docker_container:
       name: api-projet-a
       recreate: "true"
       image: student-list:latest
       networks:
        - name: student-list
       ports:
        - "5000:5000"
       volumes:
       - /home/ec2-user/ansible/student-list/simple_api/student_age.json:/data/student_age.json
                                                                                                   