---
  - name: Build image docker
    docker_image:
      name: student-list:latest
      build:
        path: /home/ec2-user/ansible/student-list/simple_api
        pull: no
      source: build
    tags: image-back

  - name: Create private container's network
    docker_network:
      name: student-list
    tags: docker-network

  - name: Start the container with the backend and connect it to the network
    docker_container:
      name: api-projet-c
      recreate: "true"
      image: student-list:latest
      networks:
        - name: student-list
       networks_cli_compatible: yes
      ports:
        - "5000:5000"
      volumes:
        - /home/ec2-user/ansible/student-list/simple_api/student_age.json:/data/student_age.json
    tags: container-back
                                                                                                   