---
    - name: Start the container with the frontend and connect it to the network
      docker_container: 
        name: ihm-projet-c
        ports:
          - "80:80"
        volumes:
          - /home/ec2-user/ansible/student-list/website:/var/www/html
        env:
          USERNAME: "toto"
          PASSWORD: "python"
        image: php:apache
        networks:
            - name: student-list
        networks_cli_compatible: yes
      tags: container-frontend

    


 



  
