---
    - name: Start the container with the frontend and connect it to the network
      docker_container: 
        name: ihm-projet-a
        ports:
          - "80:80"
        volumes:
          - /home/milica/ansible/student-list/website:/var/www/html
        env:
          USERNAME: "toto"
          PASSWORD: "python"
        image: php:apache
        networks:
            - name: student-list
      tags: container_front

    


 



  
