---
    - name: Install git
      yum:
       name: git
       state: present
       update_cache: yes

    - name: Clone the project from GitHub
      ansible.builtin.git:
        repo: "https://github.com/mili1211/ansible.git"
        force: yes
        dest:  /home/ec2-user/ansible
    