---
    - name: Install git
      apt:
       name: git
       state: present
       update_cache: yes
      tags: install_git

    # - name: Just get information about the repository whether or not it has already been cloned locally
    #   ansible.builtin.git:
    #     repo: 'https://github.com/mili1211/projetA.git'
    #     dest: /home/milica/Documents/projetA
    #     clone: no
    #     update: no
    #   register: repo_exist
    #   tags: clone_repo

    - name: Clone the project to GitHub
      ansible.builtin.git:
        repo: "https://projeta:{{ github_token }}github.com/mili1211/projetA.git"
        dest:  /home/milica/Documents/projetA
      tags: clone_repo2
      # when : 
      #   - repo_exist.changed == false