---
   - name: Update all packages
     yum:
       name: '*'
       state: latest
       update_only: yes

   - name: Install required packages
     yum:
       name:
         - yum-utils
         - amazon-linux-extras
         - docker
       state: present

   - name: Enable Docker service
     systemd:
       name: docker
       state: started
       enabled: true

   - name: Add the user to the docker group
     user:
       name: ec2-user
       append: yes
       groups: docker
   
   - name: Install Python pip for Python 2.7
     yum:
       name: python2-pip
       state: present

   - name: Install Docker module for Python 2.7
     command: pip2 install docker --ignore-installed


 



  
